name: Build image

on:
  schedule:
    - cron: '0 0 1 */6 *'
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/build.yml'


jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: -1
      - name: create tag
        run: |
          YY=$(date +%y)
          MM=$(date +%m)
          REV=0
          while git show-ref --tags | grep -q "refs/tags/${YY}.${MM}.${REV}"; do
          REV=$((REV+1))
          done
          echo "IMAGE_VERSION=${YY}.${MM}.${REV}" >> $GITHUB_ENV
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/${{ matrix.arch }}
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: |
            ghcr.io/maki8maki/zenn-docker:latest-${{ matrix.arch }}
            ghcr.io/maki8maki/zenn-docker:${{ env.IMAGE_VERSION }}-${{ matrix.arch }}

  manifest:
    runs-on: ubuntu-22.04
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: -1
      - name: create tag
        run: |
          YY=$(date +%y)
          MM=$(date +%m)
          REV=0
          while git show-ref --tags | grep -q "refs/tags/${YY}.${MM}.${REV}"; do
          REV=$((REV+1))
          done
          echo "IMAGE_VERSION=${YY}.${MM}.${REV}" >> $GITHUB_ENV
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifest images to ghcr.io
        uses: Noelware/docker-manifest-action@0.4.3
        with:
          inputs: ghcr.io/maki8maki/zenn-docker:latest,ghcr.io/maki8maki/zenn-docker:${{ env.IMAGE_VERSION }}
          images: ghcr.io/maki8maki/zenn-docker:latest-amd64,ghcr.io/maki8maki/zenn-docker:latest-arm64
          push: true
      - name: Create GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ env.IMAGE_VERSION }}
          if git show-ref --tags | grep -q "refs/tags/${TAG}"
          then
            echo "${TAG} exists. Skipped"
            exit 0
          fi
          git tag ${TAG}
          git push --tags
          gh release create ${TAG} --generate-notes
